/* Signal Atelier style: content stays separate from layout so future project and certificate updates are fast, consistent, and auditable. */
export const cvUrl = "/manus-storage/Aziz_Messaoud_CV_64f463fd.pdf";

export const profile = {
  name: "Aziz Messaoud",
  role: "Data Science Student",
  headline: "Building practical AI systems from data, models, and software.",
  body: "I turn data and models into useful, reliable applications—moving from exploration and evaluation to intelligent interfaces, APIs, and workflows.",
  availability: "Currently seeking a PFE internship in Data Science, AI Engineering, ML Engineering, Agentic AI, or AI Research.",
  email: "aziz.messaoud@esprit.tn",
  location: "Ariana, Tunisia",
  links: {
    linkedin: "https://www.linkedin.com/in/azizmessaoud/",
    github: "https://github.com/azizmessaoud/",
    portfolio: "https://azizm.me/",
    kaggle: "https://www.kaggle.com/azizmessaoud",
  },
};

export const projects = [
  {
    number: "01",
    title: "ALIA",
    eyebrow: "AI engineering · Flagship case",
    summary: "An AI-powered medical sales-training system with a real-time browser avatar and automated debrief generation.",
    details: "I owned the browser-based TalkingHead.js / Three.js avatar fallback and the standalone PPTX debrief agent. The agent turns session data into structured slide plans and ready-to-share decks.",
    outcome: "Internal synthetic-session testing produced clean decks scoring 97–99/100 in visual QA. Real trainer deployment remains future work.",
    tags: ["Three.js", "WebSockets", "TalkingHead.js", "Python", "Groq LLM"],
    visual: "/manus-storage/aziz-neural-atlas_8b3ad76f.png",
    linkLabel: "Read case",
    link: "#case-alia",
    status: "Prototype / internal test",
    featured: true,
  },
  {
    number: "02",
    title: "HR Document Intelligence",
    eyebrow: "Data science · Flagship case",
    summary: "A local-first pipeline that extracts, normalizes, validates, and routes heterogeneous HR documents for human review.",
    details: "The system combines OCR, canonical schema mapping, deterministic business rules, confidence signals, and evidence-backed anomaly flags before downstream HR integration.",
    outcome: "A working local end-to-end prototype was demonstrated with synthetic data. OCR quality and production accuracy still require broader validation.",
    tags: ["Python", "OCR", "NLP", "FastAPI", "Validation"],
    visual: "/manus-storage/aziz-document-intelligence_c04ee2bd.png",
    linkLabel: "Read case",
    link: "#case-hr",
    status: "Working prototype",
    featured: true,
  },
  {
    number: "03",
    title: "FlyRank Search Intelligence",
    eyebrow: "Applied ML · Flagship case",
    summary: "A fixed-budget review queue for deciding which pages to inspect first using anonymized search data.",
    details: "I defined the proxy label, compared it with a transparent baseline, trained a gradient-boosted-tree model, and evaluated the top-50 review queue with Precision@50.",
    outcome: "The repository reports a Precision@50 improvement from approximately 0.24 with the baseline to approximately 0.74 with the learned ranking model.",
    tags: ["Python", "Feature engineering", "GBDT", "Precision@50", "Search"],
    visual: "/manus-storage/aziz-search-intelligence_6fc48a97.png",
    linkLabel: "View code",
    link: "https://github.com/azizmessaoud/flyrank",
    status: "Research prototype",
    featured: true,
  },
  {
    number: "04",
    title: "Breast Cancer ML",
    eyebrow: "Supporting project",
    summary: "A reproducible machine-learning proof of concept covering preprocessing, model comparison, and API scaffolding.",
    details: "A technical project for demonstrating a full evaluation and deployment path. It is not a clinically validated diagnostic system.",
    outcome: "A public repository documents the pipeline and implementation boundary.",
    tags: ["Scikit-learn", "PCA", "SVM", "MLP", "Flask", "Docker"],
    visual: "/manus-storage/aziz-search-intelligence_6fc48a97.png",
    linkLabel: "View code",
    link: "https://github.com/azizmessaoud/breast-cancer-ml",
    status: "Proof of concept",
    featured: false,
  },
  {
    number: "05",
    title: "ClusterCrew Analytics",
    eyebrow: "Supporting project",
    summary: "Interactive healthcare analytics dashboards and business-intelligence reporting.",
    details: "A visual analytics project centered on decision-ready dashboards and clear communication of operational data.",
    outcome: "Live demo available.",
    tags: ["Power BI", "Data visualization", "Healthcare BI"],
    visual: "/manus-storage/aziz-document-intelligence_c04ee2bd.png",
    linkLabel: "Live demo",
    link: "https://clustercrew-analytics.onrender.com/overview",
    status: "Live demo",
    featured: false,
  },
  {
    number: "06",
    title: "InnoTravel",
    eyebrow: "Supporting project",
    summary: "A multi-platform travel-management system built with Java, JavaFX, Symfony, and MySQL.",
    details: "A full-stack academic project covering planning, booking, synchronization, and REST API integration.",
    outcome: "Public source repository available.",
    tags: ["JavaFX", "Symfony", "MySQL", "REST API"],
    visual: "/manus-storage/aziz-neural-atlas_8b3ad76f.png",
    linkLabel: "View code",
    link: "https://github.com/oumaymasaddouri/InnoTravel-PiDev-Symfony.git",
    status: "Academic project",
    featured: false,
  },
];

export const certificates = [
  { title: "Introduction to Transformer-Based NLP", issuer: "NVIDIA", year: "2025" },
  { title: "Getting Started with Deep Learning", issuer: "NVIDIA", year: "2025" },
  { title: "Fundamentals of Deep Learning", issuer: "NVIDIA", year: "2025" },
  { title: "Intermediate Machine Learning", issuer: "Kaggle", year: "2025" },
  { title: "AI Fundamentals with Capstone", issuer: "IBM SkillsBuild", year: "2025" },
  { title: "Scrum Fundamentals Certified", issuer: "SCRUMstudy", year: "2025" },
];

export const skills = ["Python", "SQL", "scikit-learn", "PyTorch", "TensorFlow", "NLP", "LLMs", "FastAPI", "Docker", "Git", "Data visualization"];
